export var fantasy_plot = [
    ["A world of people born into magnificent powers where bloodshed controls life."],
    ["A mortal has been accidentally placed onto Olympus."],
    ["Everyone is born with three wishes in life that they are not allowed to use until (input age here)."],
    ["A contest for the queen after the sudden death of said queen from a magical realm."],
    ["The bridge between the realm of the fae and mortal shrinks with each day while tensions run high."],
    ["You are the first and last person to discover the fountain of youth."],
    ["You have lived for (insert time) but have run into the option to finally be set to rest, but (blank) makes you question what you truly want."],
    ["You have lived many lifetimes, always in an endless cycle of birth and death, you finally find someone the same though."],
    ["Each night you are woken by the shouts of sailors and deckhands, the ringing of bells, and the light. But no one else has seen or heard such things."],
    ["Luck has become a hereditary trait."],
    ["Imaginary friends have gone too far, now that friend is real… but something is totally off."],
    ["Familiars” play pivotal roles in society, the strength of said creature determines your fate."],]
    
    export var romantic_plot =[
    ["You fall in love with an immortal who finds you each lifetime. You find this out by a photo album of all their “exes” who all look similar to you."],
    ["She’s a world-class thief, he’s the lead investigator. At each crime scene, there’s a note left just for him."],
    ["He’s rich beyond anyone’s wildest dreams and no one has ever been able to get close to him. All he cares about in life is perfection which he always is looking for in artwork and whatnot. But then an unruly, perfectly imperfect girl bumps into him, ruining the vase he’s bought while at a show."],
    ["She has no care for love, all she cares about is ruling with an iron fist, making her the fearsome but prosperous boss nationwide. Her newest hire has all the skills needed and perfect in every aspect, but then she’s discovered to be sent by her rival… what will she do?"],
    ["She’s motivated by blood and money and will take nearly any contract if there’s enough cash involved; he is to be the victim. But when one contract killer is trying to kill the other, what will occur?"],
    ["He ensures that everyone finds their soulmate, sometimes through much trial and error. All he’s ever done is watch idly by, but when he falls in love with a mortal meant for someone else, what is he to do?"],
    ["She’s a writer, one that writes about love and death. One night she gets a call from someone who says and acts exactly as one of her characters did… alarmed she continues to contact this person. Soon enough she finds herself in love with the character…"],
    ["She expects and wants everything to go exactly like all the fairytale stories she heard when she was younger, always with expectations high whilst being often the laughingstock. But then, she meets him…"],
    ["Everyone knows their fate, hers is quite bleak. She has no motivation and low expectations because of it, but then she is mistaken for someone else. And when she is mistaken to be who she’s not, he comes into her life and finds herself with everything she was never supposed to have."],
    ["His father is quite literally (some well-known character that would cause problems, ex: the devil, Frankenstein/ doctor Frankenstein, Vampire/Werewolf, etc.), making him a total outcast. When a new girl who heeds no warnings approaches him, what will he do?"],
    ["Their relationship was fake or at least supposed to be anyhow."],
    ["She began getting strange letters in her mail, they were yellowed and very old looking, but somehow well preserved all the same even though appearing to be from centuries ago. She eventually decides to write one back, and he receives it. They’re centuries apart but sure they’re soul mates."],
    ]
    export var mystery_plot =[
    ["You dream of murders to happen with minor details, can you save them in time? And why you?"],
    ["You can’t figure out whether you’re awake or asleep."],
    ["You have woken up after a terrible accident, at least that’s what everyone has told you. No one seems to be willing to give any details and you can’t remember the last year of your life…    "],
    ["You could’ve sworn that someone tapped you on the shoulder, but no one was there. As well you feel watched, and then you receive a letter."],
    ["A few months ago, you began to sleepwalk, but it’s not only you, but it also seems the entire town is as well."],
    ["As you’re restoring a painting you notice something strange, an engraving and the details seem to be changing."],
    ["A crime has occurred, more specifically a murder. The victim was found poisoned at the scene and as if they were sleeping, next to a bitten apple… and they were dressed as snow white. Will more follow?"],
    ["A picture is worth a thousand words, or at least that’s what they say. This one was certainly worth more than that."],
    ["A box of pictures fell onto you as you bumped a shelf, it showed a person in each and seemed to go back quite a long time… but in each, the same cat sat."],
    ["People believed to be dead or lost for years have started to show up as if they never left with no recollection of where they went either."],
    ]
    
    export var dystopian_plot =[
    ["A new law allows a person to kill someone once in their lifetime, they must fill out documents on it of course… but as well notify the soon to be victim."],
    ["People are now able to quite literally bet their lives when gambling now."],
    ["In a desperate hope to cut down on crime and population, those convicted are now entered into a lottery of sorts, the prize? Death. Those with more convictions or worse crimes have a higher likelihood of being chosen."],
    ["No one remembers why the walls were built, no one wishes to leave either though."],
    ["Black Friday has turned into a “game” for the rich. They throw trinkets and cash to the crowds of those poorer to watch the bloodbath that ensues."],
    ["Due to the high-cost and overcrowding of prisons, the government has sent prisoners to man-made islands of which there is no escape. Each island is for a certain level of prisoner, they are left to create their own society or kill each other, whichever works, I guess."],
    ["A very rare few are born without emotions; it is possible though for others to donate emotions for a time."],
    ["Physical traits are achieved through personality. Over time good deeds will create beauty."],
    ["Reincarnation is a real thing, and there are bounty hunters to track down these people. They may have been lovers, criminals, etc."],
    ["The ability to see color is a privilege of the aristocratic."],
    ["Sometimes news stations find themselves lacking, that’s why you were born. You’re what they call a Joker, your entire purpose is to do all that will make for a great story."],
    ["It is now possible to entirely swap bodies with someone else. Of course, this always results in the death of who you’re swapping with."],
    ["It is illegal to look outside from the time 11:07 pm to 6:07 am. Each person is required to enter a windowless room for those times in which the government has the ability to lock and unlock the door."],
    ["The earth turns out to be a sanctuary for an endangered species, humans. Today is the first day they are to be introduced back into the wild."],
    ]

    export var horror_story = [
    ["As the murderer in this one, you had expected them to split up, go down in hysterics, even to be at each other’s throats. Never that they would start hunting you down."],
    ["As an assassin with a sixth sense, you seek vengeance for the restless souls."],
    ["You’re a sleepwalking murderer, but when you wake up, you’re a well-known and renowned detective. You’re hunting yourself and others."],
    ["In the future virtual reality is more prevalent and even realistic than it’s ever been, an entirely new world and life. It’s often used on high profile criminals to make them live what they did from the victim’s view or their worst nightmare."],
    ["You’re finally meeting your “soulmate’s” parents, thrilled and full of glee. But as they close the door behind you, they lean in to whisper, “I’m sorry” / “Forgive me”."],
    ["You’ve been noticing strange things when you awake, new marks or stains, objects moved, new, or even missing. So, you set up a camera. After a few weeks of going over the footage, there’s something strange and unnerving.  ~Idea to further this: You wake up, get out of bed, and look into the camera… and then you die. (You kill yourself, duplicate comes in, etc.), Then someone who looks like they could be an exact clone comes in and drags out the body, cleans up, and slips back into bed."],
    ["She never seems to be able to get it right. She can’t seem to find “the one”, or someone even close to that. Little does she know it’s been the same… creature, a shapeshifter who at all costs will have her."],
    ["Each night you heard a tapping on the glass or shrill noise. One night it was too loud to ignore and persisted… soon you realized it was coming from the…"],
    ["It’s 3:33 am, a blaring siren comes from your phone with an official notification: Do not look at the moon, do not even glance at it. As well there’s an unbelievable amount of texts and posts on social media saying in some way that it’s a must-see, stunningly beautiful, once in a lifetime view."],
    ["The human mind is truly the most horrifying and gruesome thing of all."],
    ["The crow counting rhyme: One for sorrow / Two for mirth / Three for a wedding / and Four for a birth / Five for silver / Six for gold / and Seven for a secret not to be told. There are also many variations of this rhyme that you could use instead, sets up for an interesting and creepy story though."],
    ["It is now possible to know some details of your past lives, how many, how long you lived, etc. As well it’s been linked that some of your phobias are how you died…"],
    ["You’re on edge, a few weeks ago you there would be some weird occurrence. Then it was a note with messy and illegible writing. Now you can hear shrill noises, screams, shouting, indistinct. Now at seemingly the source of a scratching noise etched is a clear warning."],
    ["I kissed my wife and darling daughter goodnight… and then I awoke in a white padded room with a straight jacket on. They told me it was all just a dream."],
    ]
    export var plot_twist = [
    ["Write from the perspective of one character, but at some point, make it out to all be a dream/ simulation/ drug-induced. It could be good for thrillers or fantasy."],
    ["Write a story where one of your characters either from the start or at some point in the book are dead or presumed dead. Then have it be that they never were to shake up the story."],
    ["A character that keeps telling outlandish things, but it turns out they’re right."],
    ["A main character or “essential” character killed out of nowhere."],
    ["Have a very guilty and easy to hate a character in your story, have it be a double-cross or frame job."],
    ["A character who is mistaken for someone else but goes along with it."],
    ["A character is revealed to not be what they or the audience had thought."],
    ["An important character throughout the plot is revealed to never have truly existed."],
    ["Some devastating occurrence is caused by those whose entire goal was to fix it or keep it from occurring."],  
    ["A character believed to be unimportant to quite bland turns out to be essential and far from."],
    ["Something the character has been searching for or desperately needed was right in front of their eyes the entire time."],
    ["Have it turn out to be that the entire time some blackmail has been the cause for nearly all of a character’s actions."],
    ["It turns out the character or group of characters have been led to helping the enemy."],
]

export var random_idea = [
    ["You fall in love with an immortal who finds you each lifetime. You find this out by a photo album of all their “exes” who all look similar to you."],
    ["She’s a world-class thief, he’s the lead investigator. At each crime scene, there’s a note left just for him."],
    ["He’s rich beyond anyone’s wildest dreams and no one has ever been able to get close to him. All he cares about in life is perfection which he always is looking for in artwork and whatnot. But then an unruly, perfectly imperfect girl bumps into him, ruining the vase he’s bought while at a show."],
    ["She has no care for love, all she cares about is ruling with an iron fist, making her the fearsome but prosperous boss nationwide. Her newest hire has all the skills needed and perfect in every aspect, but then she’s discovered to be sent by her rival… what will she do?"],
    ["She’s motivated by blood and money and will take nearly any contract if there’s enough cash involved; he is to be the victim. But when one contract killer is trying to kill the other, what will occur?"],
    ["He ensures that everyone finds their soulmate, sometimes through much trial and error. All he’s ever done is watch idly by, but when he falls in love with a mortal meant for someone else, what is he to do?"],
    ["She’s a writer, one that writes about love and death. One night she gets a call from someone who says and acts exactly as one of her characters did… alarmed she continues to contact this person. Soon enough she finds herself in love with the character…"],
    ["She expects and wants everything to go exactly like all the fairytale stories she heard when she was younger, always with expectations high whilst being often the laughingstock. But then, she meets him…"],
    ["Everyone knows their fate, hers is quite bleak. She has no motivation and low expectations because of it, but then she is mistaken for someone else. And when she is mistaken to be who she’s not, he comes into her life and finds herself with everything she was never supposed to have."],
    ["His father is quite literally (some well-known character that would cause problems, ex: the devil, Frankenstein/ doctor Frankenstein, Vampire/Werewolf, etc.), making him a total outcast. When a new girl who heeds no warnings approaches him, what will he do?"],
    ["Their relationship was fake or at least supposed to be anyhow."],
    ["She began getting strange letters in her mail, they were yellowed and very old looking, but somehow well preserved all the same even though appearing to be from centuries ago. She eventually decides to write one back, and he receives it. They’re centuries apart but sure they’re soul mates."],
    ["You dream of murders to happen with minor details, can you save them in time? And why you?"],
    ["You can’t figure out whether you’re awake or asleep."],
    ["A world of people born into magnificent powers where bloodshed controls life."],
    ["A mortal has been accidentally placed onto Olympus."],
    ["Everyone is born with three wishes in life that they are not allowed to use until (input age here)."],
    ["A contest for the queen after the sudden death of said queen from a magical realm."],
    ["The bridge between the realm of the fae and mortal shrinks with each day while tensions run high."],
    ["You are the first and last person to discover the fountain of youth."],
    ["You have lived for (insert time) but have run into the option to finally be set to rest, but (blank) makes you question what you truly want."],
    ["You have lived many lifetimes, always in an endless cycle of birth and death, you finally find someone the same though."],
    ["Each night you are woken by the shouts of sailors and deckhands, the ringing of bells, and the light. But no one else has seen or heard such things."],
    ["Luck has become a hereditary trait."],
    ["Imaginary friends have gone too far, now that friend is real… but something is totally off."],
    ["Familiars” play pivotal roles in society, the strength of said creature determines your fate."]
    ["You have woken up after a terrible accident, at least that’s what everyone has told you. No one seems to be willing to give any details and you can’t remember the last year of your life…"],
    ["You could’ve sworn that someone tapped you on the shoulder, but no one was there. As well you feel watched, and then you receive a letter."],
    ["A few months ago, you began to sleepwalk, but it’s not only you, but it also seems the entire town is as well."],
    ["As you’re restoring a painting you notice something strange, an engraving and the details seem to be changing."],
    ["A crime has occurred, more specifically a murder. The victim was found poisoned at the scene and as if they were sleeping, next to a bitten apple… and they were dressed as snow white. Will more follow?"],
    ["A picture is worth a thousand words, or at least that’s what they say. This one was certainly worth more than that."],
    ["A box of pictures fell onto you as you bumped a shelf, it showed a person in each and seemed to go back quite a long time… but in each, the same cat sat."],
    ["People believed to be dead or lost for years have started to show up as if they never left with no recollection of where they went either."],
    ["A new law allows a person to kill someone once in their lifetime, they must fill out documents on it of course… but as well notify the soon to be victim."],
    ["People are now able to quite literally bet their lives when gambling now."],
    ["In a desperate hope to cut down on crime and population, those convicted are now entered into a lottery of sorts, the prize? Death. Those with more convictions or worse crimes have a higher likelihood of being chosen."],
    ["No one remembers why the walls were built, no one wishes to leave either though."],
    ["Black Friday has turned into a “game” for the rich. They throw trinkets and cash to the crowds of those poorer to watch the bloodbath that ensues."],
    ["Due to the high-cost and overcrowding of prisons, the government has sent prisoners to man-made islands of which there is no escape. Each island is for a certain level of prisoner, they are left to create their own society or kill each other, whichever works, I guess."],
    ["A very rare few are born without emotions; it is possible though for others to donate emotions for a time."],
    ["Physical traits are achieved through personality. Over time good deeds will create beauty."],
    ["Reincarnation is a real thing, and there are bounty hunters to track down these people. They may have been lovers, criminals, etc."],
    ["The ability to see color is a privilege of the aristocratic."],
    ["Sometimes news stations find themselves lacking, that’s why you were born. You’re what they call a Joker, your entire purpose is to do all that will make for a great story."],
    ["It is now possible to entirely swap bodies with someone else. Of course, this always results in the death of who you’re swapping with."],
    ["It is illegal to look outside from the time 11:07 pm to 6:07 am. Each person is required to enter a windowless room for those times in which the government has the ability to lock and unlock the door."],
    ["The earth turns out to be a sanctuary for an endangered species, humans. Today is the first day they are to be introduced back into the wild."],
    ["Write from the perspective of one character, but at some point, make it out to all be a dream/ simulation/ drug-induced. It could be good for thrillers or fantasy."],
    ["Write a story where one of your characters either from the start or at some point in the book are dead or presumed dead. Then have it be that they never were to shake up the story."],
    ["A character that keeps telling outlandish things, but it turns out they’re right."],
    ["A main character or “essential” character killed out of nowhere."],
    ["Have a very guilty and easy to hate a character in your story, have it be a double-cross or frame job."],
    ["A character who is mistaken for someone else but goes along with it."],
    ["A character is revealed to not be what they or the audience had thought."],
    ["An important character throughout the plot is revealed to never have truly existed."],
    ["Some devastating occurrence is caused by those whose entire goal was to fix it or keep it from occurring."],  
    ["A character believed to be unimportant to quite bland turns out to be essential and far from."],
    ["Something the character has been searching for or desperately needed was right in front of their eyes the entire time."],
    ["Have it turn out to be that the entire time some blackmail has been the cause for nearly all of a character’s actions."],
    ["It turns out the character or group of characters have been led to helping the enemy."],
    ["As the murderer in this one, you had expected them to split up, go down in hysterics, even to be at each other’s throats. Never that they would start hunting you down."],
    ["As an assassin with a sixth sense, you seek vengeance for the restless souls."],
    ["You’re a sleepwalking murderer, but when you wake up, you’re a well-known and renowned detective. You’re hunting yourself and others."],
    ["In the future virtual reality is more prevalent and even realistic than it’s ever been, an entirely new world and life. It’s often used on high profile criminals to make them live what they did from the victim’s view or their worst nightmare."],
    ["You’re finally meeting your “soulmate’s” parents, thrilled and full of glee. But as they close the door behind you, they lean in to whisper, “I’m sorry” / “Forgive me”."],
    ["You’ve been noticing strange things when you awake, new marks or stains, objects moved, new, or even missing. So, you set up a camera. After a few weeks of going over the footage, there’s something strange and unnerving.  ~Idea to further this: You wake up, get out of bed, and look into the camera… and then you die. (You kill yourself, duplicate comes in, etc.), Then someone who looks like they could be an exact clone comes in and drags out the body, cleans up, and slips back into bed."],
    ["She never seems to be able to get it right. She can’t seem to find “the one”, or someone even close to that. Little does she know it’s been the same… creature, a shapeshifter who at all costs will have her."],
    ["Each night you heard a tapping on the glass or shrill noise. One night it was too loud to ignore and persisted… soon you realized it was coming from the…"],
    ["It’s 3:33 am, a blaring siren comes from your phone with an official notification: Do not look at the moon, do not even glance at it. As well there’s an unbelievable amount of texts and posts on social media saying in some way that it’s a must-see, stunningly beautiful, once in a lifetime view."],
    ["The human mind is truly the most horrifying and gruesome thing of all."],
    ["The crow counting rhyme: One for sorrow / Two for mirth / Three for a wedding / and Four for a birth / Five for silver / Six for gold / and Seven for a secret not to be told. There are also many variations of this rhyme that you could use instead, sets up for an interesting and creepy story though."],
    ["It is now possible to know some details of your past lives, how many, how long you lived, etc. As well it’s been linked that some of your phobias are how you died…"],
    ["You’re on edge, a few weeks ago you there would be some weird occurrence. Then it was a note with messy and illegible writing. Now you can hear shrill noises, screams, shouting, indistinct. Now at seemingly the source of a scratching noise etched is a clear warning."],
    ["I kissed my wife and darling daughter goodnight… and then I awoke in a white padded room with a straight jacket on. They told me it was all just a dream."],
    
]