export var postIdeaList = [
  ["Start writing whatever comes to your mind."],
  ["What are 10 things that you would love to say yes to?"],
  ["List 10 things you love about your life"],
  ["List 10 beautiful things you've seen."],
  ["What’s a heartwarming thing you’ve seen?"],
  ["What angle are you not currently seeing?"],
  [
    "What is the opportunity the universe is giving me by presenting me with this situation?",
  ],
  ["How do you deal with difficulties in life?"],
  ["How would you like the world to be like?"],
  ["How do you feel about your most intimate relationship?"],
  ["What is the last book you read?"],
  ["Discuss your current passion project."],
  ["What are your core values?"],
  ["How do you see yourself?"],
  ["Write a letter to your understanding of god."],
  ["What is an important thing you've learned?"],
  ["What's a dream you've had since childhood"],
  ["What is currently holding you back from creating your best work?"],
  ["Create a morning routine chart."],
  ["What would you do if money was no object?"],
  ["If you could talk to your future self, what would you say?"],
  ["Write a letter to an alien, explaining life on earth"],
  [
    "Write a letter to your childhood best friend, telling them the story of how you came to be who you are today.",
  ],
  [
    "Write about how it feels to do something for the first time(eg. play in the snow, see the ocean, fly, etc.)",
  ],
  ["What would you do if you were alone in the world for 24 hours?"],
  ["Write down a list of random acts of kindness you could do"],
  ["Write a love letter to yourself from the perspective of a secret admirer."],
  [
    "Without thinking too much, answer the following question: What is the most present thought on your mind right now, and what does it mean?",
  ],
];
